# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test_focal_habitat_landfire.py
# Created on: 2014-09-30 19:15:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# testing model for calculating the sum of one habitat type in focal area
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
us_120evt = "us_120evt"
bacs_mask = "bacs_mask"
bacs_habitat_range = "C:\\data\\@projects\\bacs_surveys\\analysis\\habitat_analysis\\landfire_habitat_analysis.gdb\\bacs_habitat_range"
landfire-3195 = "C:\\data\\@projects\\bacs_surveys\\analysis\\habitat_analysis\\landfire_habitat_analysis.gdb\\landfire-3195"
landfire-3195-binary = "C:\\data\\@projects\\bacs_surveys\\analysis\\habitat_analysis\\landfire_habitat_analysis.gdb\\landfire-3195-binary"
landfire-3195-focal = "C:\\data\\@projects\\bacs_surveys\\analysis\\habitat_analysis\\landfire_habitat_analysis.gdb\\landfire-3195-focal"

# Process: Extract by Mask
arcpy.gp.ExtractByMask_sa(us_120evt, bacs_mask, bacs_habitat_range)

# Process: Extract by Attributes
arcpy.gp.ExtractByAttributes_sa(bacs_habitat_range, "VALUE =3195", landfire-3195)

# Process: Reclassify
arcpy.gp.Reclassify_sa(landfire-3195, "VALUE", "3195 1", landfire-3195-binary, "DATA")

# Process: Focal Statistics
arcpy.gp.FocalStatistics_sa(landfire-3195-binary, landfire-3195-focal, "Rectangle 7 7 CELL", "SUM", "DATA")

